.\"	$Id$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
.\" MA 02110-1301 USA
.\"
.Dd $Mdocdate$
.Dt DCMDFIND 1
.Os
.Sh NAME
.Nm dcmdfind
.Nd search for dive profiles
.Sh SYNOPSIS
.Nm dcmdfind
.Op Fl jsv
.Op Fl l Ar limit
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility accepts divelog files produced by
.Xr dcmd 1
and manipulates their contents: it can split individual dives into
multiple dives; join multiple dives into a single dive; or join multiple
divelogs into a single divelog, which is the default.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl l Ar limit
Limit which dives are emitted.
See
.Sx Limits
for details.
.It Fl j
Join a sequence of dives within a divelog into a single dive.
.It Fl s
Split a single dive into a sequence of dives by its surface intervals.
.It Fl v
Emit warnings during parse.
Specify twice for further debugging information.
.El
.Pp
Splitting
.Pq Fl s
is useful for establishing
.Dq canonical free dive mode ,
wherein each dive in a sequence has its own dive profile and surface
time is omitted.
Many dive computers automatically produce canonical free diving mode,
for example, the Suunto D6i.
Others, like the HW OSTC 2C, do not, and instead put all dives into one,
including surface time.
The new split dives are given a fingerprint formatted as
.Li fingerprint-num ,
where
.Dq fingerprint
is from the dive being split.
.Pp
Joining
.Pq Fl j
is useful when exporting data into Subsurface, which expects a single
dive profile.
Here, a set of dives are merged into a single one.
The new merged dive is given a fingerprint formatted as
.Li fingerprint-join ,
where
.Dq fingerprint
is from the first dive entry.
.Pp
If dives already are split,
.Fl s
does nothing; same goes with
.Fl j
and dives already being joined.
For both modes, dives not using the same dive computer as the first (by
date) are omitted.
The diver identity is ignored.
.Pp
If invoked using neither
.Fl j
nor
.Fl s ,
all dives are merged into a single divelog.
All dives must have the same dive computer as the first (by date), else
they are omitted, and duplicate fingerprints are also omitted.
.Pp
.Nm
produces output on standard output as documented in
.Xr dcmd 1 .
.Ss Limits
Processed dives may be limited with the
.Fl l Ar limit
option consisting of
.Ar key Ns = Ns Ar value
limit pairs.
The keys may be as follows:
.Bl -tag -width Ds
.It Ar dafter Ns = Ns Ar date
Dives starting after (inclusive) the
.Ar date .
.It Ar dbefore Ns = Ns Ar date
Dives starting before (inclusive) the
.Ar date .
.It Ar date Ns = Ns Ar date
Dives starting on the
.Ar date .
.It Ar dive Ns = Ns Ar pid
The dive as described by its
.Xr dcmdls 1
parse identifier.
.It Ar mode Ns = Ns Ar free|open|closed|gauge
Dives matching the
.Ar mode .
.It Ar dtafter Ns = Ns Ar datetime
Dives starting after (inclusive) the
.Ar datetime .
.It Ar dtbefore Ns = Ns Ar datetime
Dives starting before (inclusive) the
.Ar datetime .
.El
.Pp
Dates are always formatted as YYYY-mm-dd.
Date-times are formatted as YYYY-mm-ddTHH:MM.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr dcmd 1
.Sh AUTHORS
The
.Nm
utility was written by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv .
.Sh BUGS
Some data (e.g., vendor events) are ignored during conversion.
These are reported to standard error.
