.\"	$Id$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt DCMDLS 1
.Os
.Sh NAME
.Nm dcmdls
.Nd list dive profiles
.Sh SYNOPSIS
.Nm dcmdls
.Op Fl hmv
.Op Fl s Ar sort
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility accepts a set of
.Xr dcmd 1
files and collects them into an easy list view.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl h
Human-readable time spans: break down time into minutes and seconds
instead of just seconds.
This is the default.
.It Fl m
Machine-readable time spans: always seconds.
.It Fl v
Verbose parsing.
.It Fl s Ar sort
Sort listed output within a divelog.
This may be one of
.Ar datetime
for time (the default),
.Ar maxtime
for maximum dive time,
.Ar rmaxtime
for reverse maximum dive time,
.Ar maxdepth
for maximum depth,
.Ar rmaxdepth ,
for reverse maximum depth.
.El
.Pp
Lists are grouped by dive computer and diver and shown as:
.Bd -literal
divelog: [vendor] [, product] [, model] [: diver]
 [pid] [date] [time] [maxdepth] [avgtemp|-] [maxtime] [type]
.Ed
.Pp
These fields are as follows:
.Bl -tag -width Ds
.It Cm vendor
If specified, the dive computer vendor.
For example,
.Qq Suunto .
.It Cm product
If specified, the dive computer.
For example,
.Qq D6i .
.It Cm model
If specified, the model of the dive computer.
.It Cm diver
If specified, the diver.
.It Cm pid
The parse identifier.
This is unique within a series of dives and depends on input ordering.
.It Cm date
The starting date in YYYY-mm-dd format.
.It Cm time
The starting time in YYYY-mm-dd format.
.It Cm maxdepth
The maximum depth in metres.
.It Cm maxtime
The maximum time (dive time) in seconds or as a formatted time if
.Fl h
was specified.
.It Cm avgtemp
The average temperature or
.Cm \&-
if no temperatures were specified.
.It Cm type
The type of dive:
.Qq open
for open-circuit,
.Qq free
for free diving,
.Qq gauge
for gauge mode, or
.Qq closed 
for closed-circuit dives.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr dcmd 1
.Sh AUTHORS
The
.Nm
utility was written by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv .
