.\"	$Id$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
.\" MA 02110-1301 USA
.\"
.Dd $Mdocdate$
.Dt DCMDFIND 1
.Os
.Sh NAME
.Nm dcmdfind
.Nd search for dives
.Sh SYNOPSIS
.Nm dcmdfind
.Op Fl v
.Op Fl l Ar limit
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility searches for dives in
.Xr dcmd 1
files.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl l Ar limit
Limit which dives are emitted.
See
.Sx Limits
for details.
.It Fl v
Emit warnings during parse.
Specify twice for further debugging information.
.El
.Pp
If there are multiple dive computers specified, or multiple divers, the
first is selected to represent all output dives.
.Pp
All dives are merged into a single divelog, so dives must have the same
dive computer as the first (by date), else they are omitted.
Duplicate fingerprints are also omitted.
.Pp
.Nm
produces output on standard output as documented in
.Xr dcmd 1 .
.Ss Limits
Processed dives may be limited with the
.Fl l Ar limit
option consisting of
.Ar key Ns = Ns Ar value
limit pairs.
The keys may be as follows:
.Bl -tag -width Ds
.It Ar dafter Ns = Ns Ar date
Dives starting after (inclusive) the
.Ar date .
.It Ar dbefore Ns = Ns Ar date
Dives starting before (inclusive) the
.Ar date .
.It Ar date Ns = Ns Ar date
Dives starting on the
.Ar date .
.It Ar dive Ns = Ns Ar pid
The dive as described by its
.Xr dcmdls 1
parse identifier.
.It Ar mode Ns = Ns Ar free|open|closed|gauge
Dives matching the
.Ar mode .
.It Ar dtafter Ns = Ns Ar datetime
Dives starting after (inclusive) the
.Ar datetime .
.It Ar dtbefore Ns = Ns Ar datetime
Dives starting before (inclusive) the
.Ar datetime .
.El
.Pp
Dates are always formatted as YYYY-mm-dd.
The special dates
.Qq today
and
.Qq yesterday
refer to the current date and day before, respectively.
Date-times are formatted as YYYY-mm-ddTHH:MM.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To list only the current date's dives:
.Pp
.Dl dcmdfind -ldate=today *.xml | dcmdls
.Pp
To graph today's open-circuit dive:
.Pp
.Dl dcmdfind -ldate=today -lmode=open *.xml | dcmdterm
.Sh SEE ALSO
.Xr dcmd 1
.Sh AUTHORS
The
.Nm
utility was written by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv .
.Sh BUGS
Some data (e.g., vendor events) are ignored during conversion.
These are reported to standard error.
