.\"	$Id$
.\"
.\" Copyright (c) 2016--2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
.\" MA 02110-1301 USA
.\"
.Dd $Mdocdate$
.Dt DCMD 1
.Os
.Sh NAME
.Nm dcmd
.Nd download dive computer data
.Sh SYNOPSIS
.Nm dcmd
.Op Fl v
.Fl s
.Nm dcmd
.Op Fl alnv
.Op Fl d Ar device
.Op Fl f Ar fingerprint
.Op Fl i Ar ident
.Op Fl m Ar model
.Op Fl r Ar range
.Ar computer
.Sh DESCRIPTION
The
.Nm
utility downloads recent dives from a dive
.Ar computer
on a serial (or USB)
.Ar device
.Pq defaulting to Pa /dev/ttyU0
and converts them to a regular XML output format on standard output.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl a
Ignore the last-seen fingerprint and fetch all dives.
.It Fl d Ar device
The hardware device connected to the
.Ar computer .
.It Fl f Ar fingerprint
Only show the given device-specific fingerprint, if found.
Implies
.Fl a
and
.Fl n
and disables
.Fl r .
.It Fl i Ar ident
Sets these dives to the diver identified as
.Ar ident ,
which is an opaque string.
.It Fl l
Lists the dives in short format, one per line: time, type, and
fingerprint.
.It Fl m Ar model
When looking up the
.Ar computer ,
use this as the model number.
Sometimes different dive computers share the same product name and need
to be differentiated by model, e.g., the Oceanic OC1.
.It Fl n
Do not set the last-seen dive fingerprint.
.It Fl r Ar range
Process only dives within the given date
.Ar range .
Implies
.Fl a
and
.Fl n .
The range is in the format of
.Li [start[/end]] .
If empty, shows only the current day.
If just the start, shows the full start day.
If the start is empty (and just the range end), shows from the beginning
of time to the end.
The start and end format is
.Li YYYY-MM-DD[THH:MM:SS] .
.It Fl s
Shows all known device computers instead of trying to download data.
This lists the vendor, then the product.
If there are multiple vendor/product pairs of the same name, the model
number is also printed in parenthesis.
.It Fl v
Increase verbosity.
One more, emits informational messages.
Twice, debugging messages.
Three times, inundation.
.It Ar computer
The case-insensitive full vendor and product, e.g.,
.Dq suunto d6i
or
.Dq cressi leonardo .
You can also just specify the product, e.g.,
.Dq d6i ,
but if there are multiple vendors with the same product, they may
conflict.
You may need to specify a model with
.Fl m
if there are multiple vendor/product pairs with the same name.
.El
.Pp
In the default behaviour (i.e.,
.Fl s
was not specified), the dive computer connected to
.Ar device
is opened and its contents downloaded and formatted as XML.
.Pp
.Em Be careful :
many dive computers don't charge when connected to a computer.
Plug it in, suck down your data, and unplug it as soon as possible.
.Pp
The last-seen fingerprint is stored in
.Pa ~/.divecmd/DEVICE ,
where
.Dq DEVICE
is the dive computer device name and diver identifier rendered as a
filename, for example,
.Pa ~/.divecmd/suunto_d6i-26_kristaps
.Pq vendor, product, model, diver .
It is used to get (and/or initialise) and set the last known dive.
This suppresses old dives from being re-downloaded every time
.Nm
is invoked.
The
.Pa DEVICE
file is a binary fingerprint.
The
.Fl a
and
.Fl n
flags restrict usage of this file.
If
.Pa ~/.divecmd
does not exist, it is created.
.Ss Output
.Nm
outputs an XML file describing the dive.
In this description, attributes offset by brackets
.Pq Do \(lB Dc and Do \(rB Dc
are optional.
Optional elements are specifically marked as such.
Values with
.Dq xxx
are floating-point,
.Dq nnn
are integral,
.Dq ss
are integral seconds, and
.Dq uuu
are unit-interval floating point.
All units are metric.
.Em Note :
this format may change as the tool progresses, my diving progresses, and
I acquire more dive computers.
If you want good support, send me diving with a new computer!
.Pp
The XML output is arranged as follows, with comments inline:
.Bd -literal
<?xml version="1.0" encoding="UTF-8" ?>
<divelog program="dcmd" version="0.0.1"
 vendor="zzzz" product="zzzz" model="nnn"
 [diver="zzzz"]>
  <dives>
.Ed
.Pp
The values to this element relate to the dive computer hardware, the
diver
.Pq if given by Fl i
and the software version.
Now begins the dives.
There may be multiple dives, which is often the case with free-diving or
any time multiple dives have been exported.
.Bd -literal
    <dive number="n"
     [date="yyyy-mm-dd" time="hh:mm:ss"]
     [duration="ss"] [mode="YYYY"]>
.Ed
.Pp
Each dive is numbered in a device-specific way.
The time, if supported by the device, is in local time.
The dive time, also if supported, is always shown in seconds.
The mode is one of
.Li freedive
.Pq obviously free-diving ,
.Li gauge
.Pq recorded directly from a tank gauge ,
.Li opencircuit
.Pq open-circuit standard diving ,
or
.Li closedcircuit
.Pq closed-circuit rebreathing .
.Bd -literal
      <fingerprint>xxx-yyy-zzz</fingerprint>
.Ed
.Pp
A unique, alphanumeric fingerprint for the dive.
.Bd -literal
      <gasmixes>
        <gasmix num="NNN" [o2="xxx" n2="xxx" he="xxx"] />
      </gasmixes>
.Ed
.Pp
Gas mixes (in percent) used in this dive (optional element).
.Pq Not to be confused with tanks.
A gas mix should have its mix value, but that's not guaranteed: it will
at least show the mix number.
This number may later be referenced in the samples when switching gases,
or by the tanks.
.Bd -literal
      <tanks>
        <tank num="nnn" [gasmix="nnn"]
         [volume="xxx" [workpressure="xxx"]]
         beginpressure="xxx" endpressure="xxx" />
      </tanks>
.Ed
.Pp
Tanks (optional element).
A tank defines the tank parameters itself, including the referenced
gasmix (also if applicable), volume and work pressure, and the start and
end pressure over the course of the dive.
.Bd -literal
      <depth [max="xxx"] [mean="xxx"] />
.Ed
.Pp
The depth field (optional).
This sets either (or both) the maximum and average non-zero depth.
And now, the samples...
.Bd -literal
      <samples>
        <sample time="ss">
         [<rbt value="ss" />]
	 [<vendor type="nnn">[value]</vendor>]
         [<depth value="xxx" />]
         [<temp value="xxx" />]
         [<pressure value="xxx" tank="nnn" />]
         [<deco depth="xxx" type="zzz" duration="ss" />]
         [<gaschange mix="nnn" />]
         [<event type="event" />]
        </sample>
      </samples>
.Ed
.Pp
The sample time is in seconds from the dive start and is
always specified.
The remaining optional sub-elements are as follows.
Note that sub-elements may be repeated or have multiple invocations,
such as multiple values of
.Li pressure
for different tanks.
.Bl -tag -width Ds
.It Li rbt
Remaining bottom time
.Pq Dq RBT
.Pq seconds
at sampling time.
.It Li vendor
Vendor-specific information of
.Li type .
If the given event consists of no data, it will simply be a self-closed
XML tag.
Otherwise, it will consist of rows of 16 bytes of hexadecimally encoded
byte values, e.g.,
.Dq hello
in ASCII being
.Dq 68656C6C6F .
.It Li depth
Depth (metres) at sampling time.
.It Li temp
Temperature (Celsius) at sampling time.
.It Li pressure
Tank pressure (in bar).
References a tank number in the
.Li <tanks>
section.
.It Li gaschange
Change of gas mixture.
This refers to the
.Li mix
corresponding to the
.Li <gasmix num="nnn">
in the
.Li <gasmixes>
set for the dive.
.It Li deco
A decompression notice.
The
.Li type
attribute may be one of
.Dq ndl ,
.Dq safetystop ,
.Dq decostop ,
or
.Dq deepstop .
Duration is in seconds.
.It Li event
A generic event.
This may have the
.Li type
set to one of
.Dq none ,
.Dq decostop ,
.Dq rbt ,
.Dq ascent ,
.Dq ceiling ,
.Dq workload ,
.Dq transmitter ,
.Dq violation ,
.Dq bookmark ,
.Dq surface ,
.Dq safetystop ,
.Dq gaschange ,
.Dq safetystop_voluntary ,
.Dq safetystop_mandatory ,
.Dq deepstop ,
.Dq ceiling_safetystop ,
.Dq floor ,
.Dq divetime ,
.Dq maxdepth ,
.Dq olf ,
.Dq po2 ,
.Dq airtime ,
.Dq rgbm ,
.Dq heading ,
.Dq tissuelevel ,
or
.Dq gaschange2 .
No additional information is provided at this time.
.El
.Pp
In theory, it's possible for a sample to have no inner elements at all,
but in all cases I've observed, there is at least one.
.Po
Usually the
.Li <depth>
element is specified for all samples, but of course this isn't
guaranteed.
.Pc
.Bd -literal
    </dive>
  </dives>
</divelog>
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
The
.Nm
utility was forked by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv ,
from the exemplar utility bundled with
.Xr libdivecomputer 3 ,
written by
.An Jef Driesen
.Mt jef@libdivecomputer.org .
