.\"	$Id$
.\"
.\" Copyright (c) 2016 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\" 
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
.\" MA 02110-1301 USA
.\" 
.Dd $Mdocdate: January 5 2017 $
.Dt DIVECMD 1
.Os
.Sh NAME
.Nm divecmd
.Nd download dive computer data
.Sh SYNOPSIS
.Nm divecmd
.Op Fl v
.Fl s
.Nm divecmd
.Op Fl alnv
.Op Fl d Ar device
.Op Fl f Ar fingerprint
.Ar computer
.Sh DESCRIPTION
The
.Nm
utility downloads recent dives from a dive
.Ar computer
on a serial (or USB)
.Ar device
.Pq defaulting to Pa /dev/ttyU0
and converts them to a regular XML output format on standard output.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl a
Ignore the last-seen fingerprint and fetch all dives.
.It Fl l
Lists the dives in short format, one per line: time, type, and
fingerprint.
.It Fl n
Do not set the last-seen dive fingerprint.
.It Fl s
Shows all known device computers instead of trying to download data.
.It Fl v
Increase verbosity.
One more, emits informational messages.
Twice, debugging messages.
Three times, inundation.
.It Fl d Ar device
The hardware device connected to the
.Ar computer .
.It Fl f Ar fingerprint
Only show the given device-specific fingerprint, if found.
Implies
.Fl a
and
.fl n .
.It Ar computer
The case-insensitive full vendor and product, e.g.,
.Dq suunto d6i
or
.Dq cressi leonardo .
You can also just specify the product, e.g.,
.Dq d6i ,
but if there are multiple vendors with the same product, they may
conflict.
.El
.Pp
In the default behaviour (i.e.,
.Fl s
was not specified), the dive computer connected to
.Ar device
is opened and its contents downloaded and formatted as XML.
.Pp
.Em Be careful :
many dive computers don't charge when connected to a computer.
Plug it in, suck down your data, and unplug it as soon as possible.
.Pp
By default, the file
.Pa ~/.divecmd/DEVICE ,
where
.Dq DEVICE
is the dive computer device name rendered as a filename,
is used to get (and/or initialise) and set the last known dive.
This suppresses old dives from being re-downloaded every time
.Nm
is invoked.
The
.Pa DEVICE
file is a binary fingerprint.
The
.Fl a
and
.Fl n
flags restrict usage of this file.
If
.Pa ~/.divecmd
does not exist, it is created.
.Ss Output
.Nm
outputs an XML file describing the dive.
In this description, attributes offset by brackets
.Pq Do \(lB Dc and Do \(rB Dc
are optional.
Optional elements are specifically marked as such.
Values with
.Dq xxx
are floating-point,
.Dq nnn
are integral, and
.Dq uuu
are unit-interval floating point.
All units are metric.
.Em Note :
this format may change as the tool progresses, my diving progresses, and
I acquire more dive computers.
If you want good support, send me diving with a new computer!
.Pp
The XML output is arranged as follows, with comments inline:
.Bd -literal
<?xml version="1.0" encoding="UTF-8" ?>
<divelog program="divecmd" version="0.0.1">
  <dives>
.Ed
.Pp
Now begins the dives.
There may be multiple dives, which is often the case with free-diving or
any time multiple dives have been exported.
.Bd -literal
    <dive number="n"
     [date="yyyy-mm-dd" time="hh:mm:ss"]
     [duration="ss"] [mode="YYYY"]>
.Ed
.Pp
Each dive is numbered in a device-specific way.
The time, if supported by the device, is in local time.
The dive time, also if supported, is always shown in seconds.
The mode is one of
.Li freedive
.Pq obviously free-diving ,
.Li gauge
.Pq recorded directly from a tank gauge ,
.Li opencircuit
.Pq open-circuit standard diving ,
or
.Li closedcircuit
.Pq closed-circuit rebreathing .
.Bd -literal
      <fingerprint>xxx-yyy-zzz</fingerprint>
.Ed
.Pp
A unique, alphanumeric fingerprint for the dive.
.Bd -literal
      <gasmixes>
        <gasmix num="NNN" [o2="xxx" n2="xxx" he="xxx"] />
      </gasmixes>
.Ed
.Pp
Gas mixes (in percent) used in this dive (optional element).
.Pq Not to be confused with tanks.
A gas mix should have its mix value, but that's not guaranteed: it will
at least show the mix number.
This number may later be referenced in the samples when switching gases,
or by the tanks.
.Bd -literal
      <tanks>
        <tank num="nnn" [gasmix="nnn"]
         [volume="xxx" [workpressure="xxx"]]
         beginpressure="xxx" endpressure="xxx" />
      </tanks>
.Ed
.Pp
Tanks (optional element).
A tank defines the tank parameters itself, including the referenced
gasmix (also if applicable), volume and work pressure, and the start and
end pressure over the course of the dive.
.Bd -literal
      <depth [max="xxx"] [mean="xxx"] />
.Ed
.Pp
The depth field (optional).
This sets either (or both) the maximum and average non-zero depth.
And now, the samples...
.Bd -literal
      <samples>
        <sample time="ss">
         [<depth value="xxx" />]
         [<temp value="xxx" />]
         [<pressure value="xxx" tank="nnn" />]
        </sample>
      </samples>
.Ed
.Pp
The sample time is in seconds from the dive start and is
always specified.
The remaining optional sub-elements are as follows:
.Bl -tag -width Ds
.It Li depth
Depth (metres) at sampling time.
.It Li temp
Temperature (celsiu) at sampling time.
.It Li pressure , tank
Tank pressure (in bar).
References a tank number in the
.Li <tanks>
section.
.El
.Pp
In theory, it's possible for a sample to have no inner elements at all,
but in all cases I've observed, there is at least one.
.Po
Usually the
.Li <depth>
element is specified for all samples, but of course this isn't
guaranteed.
.Pc
.Bd -literal
    </dive>
  </dives>
</divelog>
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
The
.Nm
utility was forked by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv ,
from the exemplar utility bundled with
.Xr libdivecomputer 3 ,
written by
.An Jef Driesen
.Mt jef@libdivecomputer.org .
