.\"	$Id$
.\"
.\" Copyright (c) 2016 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\" 
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
.\" MA 02110-1301 USA
.\" 
.Dd $Mdocdate$
.Dt DIVECMD 1
.Os
.Sh NAME
.Nm divecmd
.Nd download dive computer data as structured XML files
.Sh SYNOPSIS
.Nm divecmd
.Op Fl v
.Fl l
.Nm divecmd
.Op Fl v
.Fl d Ar computer
.Op Ar device
.Sh DESCRIPTION
The
.Nm
utility downloads data from a dive
.Ar computer
on a serial (or USB)
.Ar device
.Pq defaulting to Pa /dev/ttyU0
and converts it to a regular XML output format on standard output.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl v
Increase verbosity.
One more, emits informational messages.
Twice, debugging messages.
Three times, inundation.
.It Fl l
Lists all known device computers instead of trying to download data.
.It Fl d Ar computer
The case-insensitive full vendor and product, e.g.,
.Dq suunto d6i
or
.Dq cressi leonardo .
You can also just specify the product, e.g.,
.Dq d6i ,
but if there are multiple vendors with the same product, they may
conflict.
.El
.Pp
In the default behaviour (i.e.,
.Fl l
was not specified), the dive computer connected to
.Ar device
is opened and its contents downloaded and formatted as XML.
.Ss Output
.Nm
outputs an XML file describing the dive.
All units are metric.
.Em Note :
this format may change as the tool progresses, my diving progresses, and
I acquire more dive computers.
If you want good support, send me diving with a new computer!
.Pp
The output is arranged as follows, with comments inline:
.Bd -literal
<?xml version="1.0" encoding="UTF-8" ?>
<divelog program="divecmd" version="0.0.1">
  <dives>
.Ed
.Pp
Now begins the dives.
There may be multiple dives, which is often the case with free-diving or
any time multiple dives have been exported.
.Bd -literal
    <dive number="n" date="yyyy-mm-dd"
     time="hh:mm:ss" duration="mm:ss">
.Ed
.Pp
Each dive is numbered in a device-specific way.
The time is usually in local time, but it depends upon the device.
The dive time is always shown by minutes and seconds: it will not show
an hour field.
.Bd -literal
      <fingerprint>xxx-yyy-zzz</fingerprint>
.Ed
.Pp
A unique, alphanumeric fingerprint for the dive.
.Bd -literal
      <cylinder [o2="xxx"] />
.Ed
.Pp
Cylinders used and the gas mix.
Multiple cylinders are indicated by several entries.
If the mix is regular air (\(gt20%, \(le22%), the mix is omitted.
.Pq Helium is not yet supported.
.Bd -literal
      <divecomputer dctype="xxxx">
        <depth max="xxx" mean="yyy" />
.Ed
Now the information from the dive computer.
First, the type of dive recorded.
This can be
.Li Freedive
.Pq obviously free-diving ,
.Li Gauge
.Pq recorded directly from a tank gauge ,
.Li Opencircuit
.Pq open-circuit standard diving ,
.Li Closedcircuit
.Pq closed-circuit rebreathing 
or
.Li unknown .
The mean depth is zero if it is not supported by your device.
And now, the samples...
.Pp
.Bd -literal
        <sample time="mm:ss" depth="xx" temp="xx" />
.Ed
.Pp
The sample time is in minutes and seconds from the dive start and both
depth and temperature are metric.
.Bd -literal
      </divecomputer>
    </dive>
  </dives>
</divelog>
.Ed
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
The
.Nm
utility was forked by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv ,
from the exemplar utility bundled with
.Xr libdivecomputer 3 .
